# Generated by Django 5.1.8 on 2025-09-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='interviewer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='interviewer',
            name='last_name',
        ),
    ]
