# Generated by Django 5.1.8 on 2025-09-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_remove_interviewer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewer',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
