# Generated by Django 5.1.8 on 2025-09-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interviewer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='name',
            field=models.CharField(default='Norma Fisher', max_length=100),
        ),
    ]
